title: User Upload Frequency Graph
description: This add-on will generate a graph that shows the upload frequency for a particular user. 
instructions: ''
type: object
documents: []
properties:
  user_id:
    title: User ID
    type: integer
required:
  - user_id
categories:
  - statistical

